# Site Info
title:              "R.Z"
description:        |
  **Rex,**
  
  **a professional in chilling with myself**
  
  **as well as** 
  
  **a numb analyst with styles**
  
copyright:          trexwithoutt
google_verify:      epFgX0s_0RM3CdjwFcsewfXzPov2g8s9ZBOLyaIUH-o # Put your Google Verification here
google_analytics:   UA-XXXXXXX-X # Put your Google Analytics code

# Author Info
author_name:        "Rex Zhou" # Your name here
author_email:       rexzhe1230@gmail.com # Your email here
author_gravatar:    2b38b1b0e7e08b69379bd61582adf0c8 # Your Gravatar md5 hash here for logo
facebook_username: "rex.zhou.50"
linkedin_username: "rex-zhou-4bb38a148"
instagram_username: "trexwithoutt"
pinterest_username: "rex0138"
github_username:  "trexwithoutt"

# Site Settings
url:                https://trexwithoutt.github.io/ # main url
baseurl:            # for gh-pages
permalink:          /notes/:title # Post permalink
timezone:           America/Chicago # Asia/Kuala_Lumpur # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
mathjax:            true  # enables support for mathjax - set to false to disable

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile" ]
gems:
  - jekyll-sitemap



defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
